import type {NextPage} from 'next';
import Head from 'next/head';
import ProjectList from '../components/ProjectList';
import Typed from 'typed.js';
import {useEffect, useRef} from 'react';

const Home: NextPage = () => {
  const typedEl = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    let typed: Typed | null = null;

    if (typedEl.current) {
      typed = new Typed(typedEl.current, {
        strings: [
          'Rezuan Kassim',
          'Web Developer',
          'Laravel Developer',
          'Front-end Developer',
          'React Developer',
          'Vue Developer',
        ],
        startDelay: 300,
        typeSpeed: 50,
        backSpeed: 100,
        backDelay: 100,
        smartBackspace: true,
        loop: true,
        showCursor: true,
      });
    }

    return () => {
      typed?.destroy();
    };
  }, []);

  return (
    <div>
      <Head>
        <title>Rez. | Web Developer</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className="mx-auto max-w-5xl">
        <div className="mt-28">
          <span>Hey, I&apos;m</span>

          <h1 className="mt-4 bg-gradient-to-r from-[#9845E8] via-[#33D2FF] to-[#DD5789] bg-clip-text text-8xl font-medium text-transparent">
            <span ref={typedEl}></span>
          </h1>

          <p className="mt-6 text-justify">
            Based in <span className="font-medium text-[#9845E8]">Sabah, Malaysia</span>. I enjoy
            creating things that live on the internet, whether that be websites, applications, or
            anything in between. I&apos;ve manage to gain a decent amount of experience and valuable
            knowledge from all different kinds of fields throughout my projects/work.
          </p>

          <a
            href="#"
            className="mt-10 inline-flex items-center gap-x-3 duration-300 ease-in-out hover:text-[#9845E8]"
          >
            <span>Say hi</span>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fillRule="evenodd"
                d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
                clipRule="evenodd"
              />
            </svg>
          </a>
        </div>

        <div className="mt-32">
          <span className="text-lg font-light uppercase">Featured Projects</span>

          <ProjectList />
        </div>

        <hr className="my-24 border-t-[#C4C4C4]" />
      </main>
    </div>
  );
};

export default Home;
